version: '3.8'

services:
  proxy:
    build: ./proxy 
    container_name: doc_parser_proxy_server
    ports:
      - "6060:6060" 
    environment:
      - VLLM_TIMEOUT=30 #seconds
      - VLLM_URL=http://vllm:8000/v1/chat/completions
      - LOG_LEVEL=DEBUG
      - SAVE_INVALID_FILES=true
      - MAX_IMAGES=2
    #depends_on:
    #  vllm:
    #    condition: service_healthy 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6060/health"]
      interval: 60s
      timeout: 10s
      retries: 5
    logging:
      options:
        max-size: 50mb
        max-file: 100
    restart: unless-stopped
    networks:
      - default_network
      - internal_network

  
  vllm:
    image: vllm/vllm-openai:nightly
    container_name: doc_parser-vllm_gemma
    command: >
      --model=Qwen/Qwen2.5-VL-3B-Instruct
      --gpu-memory-utilization=0.95
      --max-num-seqs=2
      --max-model-len=4096
      --dtype=half
      --trust-remote-code
      --generation-config=auto
      --override-generation-config='{"temperature": 0.0, "top_k": 20, "top_p": 0.8}'
      --mm-processor-kwargs='{"min_pixels": 784, "max_pixels": 1003520, "fps": 1}'
    volumes:
      - doc_parser_hf_cache:/root/.cache/huggingface
    environment:
      - HUGGING_FACE_HUB_TOKEN=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
      #- VLLM_LOGGING_LEVEL=DEBUG
      #- VLLM_USE_FLASHINFER_SAMPLER=0
      - TEMPERATURE=0.0
      - TOP_K=20
      - TOP_P=0.8
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu] 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 60s
      timeout: 10s
      retries: 5
    logging:
      options:
        max-size: 50mb
        max-file: 100
    restart: unless-stopped
    networks:
      - internal_network

volumes:
  doc_parser_hf_cache:

networks:
  default_network:
    driver: bridge
  internal_network:
    internal: true